databases:
  - name: djangovida
    plan: free
    databaseName: djangovida
    user: dsfargeg

services:
  - type: web
    plan: free
    name: djangovida
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'cd djangovida && python -m gunicorn djangovida.wsgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: djangovida
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
